/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pawelch' at '1/20/15 11:48 PM' with Gradle 2.2.1
 *
 * @author pawelch, @date 1/20/15 11:48 PM
 */
public class Library {

  public boolean someLibraryMethod() {
    return true;
  }
}
